elecData <- read.table("household_power_consumption.txt", header = TRUE, sep = ";", na.strings = "?", stringsAsFactors = FALSE)
library(dplyr)
elecData <- tbl_df(elecData)
usefulData <- filter(elecData, Date == "1/2/2007"|Date == "2/2/2007")
library(lubridate)
DateTime <- dmy_hms(paste(usefulData$Date, usefulData$Time))
newData <- cbind(usefulData, DateTime)
hist(newData[,3], col = "red", main = "Global Active Power", xlab = "Global Active Power (kilowatts)")
dev.copy(png, file = "plot1.png")
dev.off()
