elecData <- read.table("household_power_consumption.txt", header = TRUE, sep = ";", na.strings = "?", stringsAsFactors = FALSE)
library(dplyr)
elecData <- tbl_df(elecData)
usefulData <- filter(elecData, Date == "1/2/2007"|Date == "2/2/2007")
library(lubridate)
DateTime <- dmy_hms(paste(usefulData$Date, usefulData$Time))
newData <- cbind(usefulData, DateTime)
with(newData, plot(DateTime, Global_active_power, type = "n", xlab = "", ylab = "Global Active Power (kilowatts)"))
lines(newData$DateTime, newData$Global_active_power)
dev.copy(png, file = "plot2.png")
dev.off()
