elecData <- read.table("household_power_consumption.txt", header = TRUE, sep = ";", na.strings = "?", stringsAsFactors = FALSE)
library(dplyr)
elecData <- tbl_df(elecData)
usefulData <- filter(elecData, Date == "1/2/2007"|Date == "2/2/2007")
library(lubridate)
DateTime <- dmy_hms(paste(usefulData$Date, usefulData$Time))
newData <- cbind(usefulData, DateTime)
png("plot4.png", width = 480, height = 480)
par(mfrow = c(2,2))
with(newData, plot(DateTime, Global_active_power, type = "n", xlab = "", ylab = "Global Active Power"))
lines(newData$DateTime, newData$Global_active_power)
lines(newData$DateTime, newData$Global_active_power)
with(newData, plot(DateTime, Voltage, type = "n", xlab = "datetime", ylab = "Voltage"))
lines(newData$DateTime, newData$Voltage)
with(newData, plot(DateTime, Sub_metering_1, type = "n", xlab = "", ylab = "Energy sub metering"))
lines(newData$DateTime, newData$Sub_metering_1)
lines(newData$DateTime, newData$Sub_metering_2, col = "red")
lines(newData$DateTime, newData$Sub_metering_3, col = "blue")
legend("topright", pch = c(NA, NA, NA), col = c("black", "red", "blue"), lty = c(1,1,1), legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
with(newData, plot(DateTime, Global_reactive_power, type = "n", xlab = "datetime", ylab = "Global_reactive_power"))
lines(newData$DateTime, newData$Global_reactive_power)
dev.off()